version: "3.3"
services:
    trankit:
        build:
            context: .
        container_name: 'fnbr-embedding'
        restart: unless-stopped
        ports:
            - ${WWW_PORT}:80
        volumes:
            - ${DOCUMENT_ROOT}:/code
